import { Helmet } from "react-helmet";
import { Text, Img, Heading, Button } from "../../components";
import Footer1 from "../../components/Footer1";
import Header1 from "../../components/Header1";
import NewYorkProfile from "../../components/NewYorkProfile";
import BakudiscountColumnTwo from "./BakudiscountColumnTwo";
import BakudiscountColumnexplore from "./BakudiscountColumnexplore";
import BakudiscountDivhomepageh from "./BakudiscountDivhomepageh";
import React from "react";export default function BakudiscountPage() { 
   return (  
      <>     
       <Helmet>     
           <title>BookForme</title>  
                 <meta name="description" content="Web site created using create-react-app" />    
                   </Helmet>      
                   <div className="w-full bg-white-a700">    
                        <div className="flex flex-col gap-[106px] md:gap-[79px] sm:gap-[53px]">  
                                  <div className="relative h-[2288px]">      
                                          <div className="absolute bottom-0 left-0 right-0 top-0 m-auto flex h-max flex-1 flex-col items-center gap-[76px] bg-white-a700 md:gap-[57px] sm:gap-[38px]">     
                                                     <div className="self-stretch">   
                                                                   <div className="bg-red-800 px-14 md:px-5">    
                                                          <div className="mb-[34px]">                
                                                                <div className="mr-[62px] flex items-start md:mr-0">     
                                                                                   <Img                        
                                                                                   src="images/img_bookforme_02_03.png"              
                                                                                             alt="Bookforme02thre"               
                                                                                                      className="relative z-[1] h-[124px] w-[12%] self-center object-contain" />                  
                                                                                                          <Header1 />             
                                                                                                                 </div>
                                                                                                                 <div className="mr-[38px] flex px-6 md:mr-0 sm:px-5">    
                                                                                                                          <Button  
                                                                                                                                    leftIcon={<Img src="images/img_icon_white_a700.svg"
                                                                                                                                       alt="Icon" className="h-[16px] w-[16px]" />}                        
                                                                                                                                       className="min-w-[98px] gap-2 rounded-[10px] px-4 font-kantumruypro font-medium"   >
                                                                                                                                                                Flights  </Button>         
                                                                                                                                                                             <div className="flex gap-2 rounded-[10px] p-2">  
                                                                                                                                                                                <Img src="images/img_icon_white_a700_16x16.svg" alt="Icon" className="h-[16px] w-[16px]" />          
                                                                                                                                                                                              <Text as="p" className="font-kantumruypro text-[13.2px] font-medium text-white-a700">       
                                                                                                                                                                                                                   Hotels                
                                                                                                                                                                                                                           </Text>           
                                                                                                                                                                                                                                      </div>             
                                                                                                                                                                                                                                             </div>   
                                                                                                                                                                                                                                                 </div>      
                                                                                                                                                                                                                                                           </div>          
                                                                                                                                                                                                                                                                 <BakudiscountDivhomepageh />   
                                                                                                                                                                                                                                                                            </div>             
                                                                                                                                                                                                                                                                             <BakudiscountColumnexplore />     
                                                                                                                                                                                                                                                                                     <div className="container-xs mb-[376px] flex flex-col items-start px-7 md:px-5">         
                                                                                                                                                                                                                                                                                             <Heading size="heading5xl" as="h4" className="text-[24px] font-bold text-gray-900_02 md:text-[22px]">    
                                                                                                                                                                                                                                                                                                            Nearby destinations              
                                                                                                                                                                                                                                                                                                              </Heading>          
                                                                                                                                                                                                                                                                                                                  </div>        
                                                                                                                                                                                                                                                                                                                      </div>     
                                                                                                                                                                                                                                                                                                                             <div className="container-xs absolute bottom-px left-0 right-0 my-auto grid grid-cols-3 justify-center gap-4 px-7 md:grid-cols-2 md:px-5 sm:grid-cols-1">       
                                                                                                                                                                                                                                                                                                                                     <NewYorkProfile />     
                                                                                                                                                                                                                                                                                                                                              <div className="relative h-[194px] w-full content-center rounded-lg md:h-auto">      
                                                                                                                                                                                                                                                                                                                                                          <Img    src="images/img_977408_jpg.png"   alt="977408jpg"
                                                                                                                                                                                                                                                                                                                                                            className="mx-auto h-[194px] w-full flex-1 rounded-lg object-cover" 
                                                                                                                                                                                                                                                                                                                                                            />                <div className="absolute bottom-[-0.66px] left-0 right-0 m-auto flex-1">          
                                                                                                                                                                                                                                                                                                                                                                    <div className="h-[52px] bg-gradient" />          
                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-gradient1 p-3.5">              
                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-1 flex flex-col items-start">         
                                                                                                                                                                                                                                                                                                                                                                                                   <Text className="text-[16px] font-normal text-white-a700">Las Vegas</Text>            
                                                                                                                                                                                                                                                                                                                                                                                                             <Text className="text-[11.63px] font-normal text-white-a700">914 things to do</Text>     
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>              
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>          
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>     
                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>    
                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="relative h-[194px] w-full content-center rounded-lg md:h-auto">   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <Img    src="images/img_689598_jpg.png"    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       alt="689598jpg" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="mx-auto h-[194px] w-full flex-1 rounded-lg object-cover"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         />               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="absolute bottom-[-0.66px] left-0 right-0 m-auto flex-1">               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div className="h-[52px] bg-gradient" />            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="bg-gradient1 p-3.5">        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-1 flex flex-col items-start">       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <Text className="text-[16px] font-normal text-white-a700">Key West</Text>    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <Text className="text-[11.63px] font-normal text-white-a700">261 things to do</Text>          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="relative h-[194px] w-full content-center md:h-auto"> 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <Img  src="images/img_976725_jpg.png"  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alt="976725jpg"  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               className="mx-auto h-[194px] w-full flex-1 rounded-lg object-cover" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="absolute bottom-[-0.65px] left-0 right-0 m-auto flex-1">      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="h-[52px] bg-gradient" />      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-gradient1 p-3.5">       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="mt-1 flex flex-col items-start">                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Text className="text-[16px] font-normal text-white-a700">San Diego</Text>         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <Text className="text-[11.63px] font-normal text-white-a700">371 things to do</Text>          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="relative h-[194px] w-full content-center md:h-auto">  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Img                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            src="images/img_977388_jpg.png"           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 alt="977388jpg"           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="mx-auto h-[194px] w-full flex-1 rounded-lg object-cover"    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="absolute bottom-[-0.65px] left-0 right-0 m-auto flex-1">     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div className="h-[52px] bg-gradient" />            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className="bg-gradient1 p-3.5">        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex flex-col items-start gap-1 self-end">        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Text className="text-[15.5px] font-normal text-white-a700">Miami</Text>    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text className="text-[11.63px] font-normal text-white-a700">775 things to do</Text>             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div className="relative h-[194px] w-full content-center md:h-auto"> 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Img src="images/img_976879_jpg.png"  alt="976879jpg"    className="mx-auto h-[194px] w-full flex-1 rounded-lg object-cover"  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div className="absolute bottom-[-0.65px] left-0 right-0 m-auto flex-1">    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div className="h-[52px] bg-gradient" />               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-gradient1 p-3.5">            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex flex-col items-start gap-0.5 self-end">            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text className="text-[16px] font-normal text-white-a700">New Orleans</Text>                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text className="text-[11.63px] font-normal text-white-a700">547 things to do</Text>           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>      
                                                                                                                                                                                                                                                                                </div>      
                                                                                                                                                                                                                                                                                    <BakudiscountColumnTwo />      
                                                                                                                                                                                                                                                                                        <Footer1 />   
                                                                                                                                                                                                                                                                                             </div>    
                                                                                                                                                                                                                                                                                               </div>   
                                                                                                                                                                                                                                                                                                </>  );}